name: "@src"
description: ""
namespace: "Aywan\\JsonAst\\"

# "Public API" of the modulite: classes, functions, constants, etc.
# Symbols not listed here will be internal.
export:
  - "JsonAstException"
  - "JsonAstParser"
  - "JsonAstTree"
  - "Node\\ArrayNode"
  - "Node\\ObjectNode"
  - "Node\\ScalarNode"
  - "Tokenizer\\Token"
  - "Tokenizer\\TokenData"
  - "Tokenizer\\TokenType"
  - "Tokenizer\\TokenizerException"

# Class members to exclude, they override "export".
force-internal:

# Dependencies: other modulites, global classes, defines, etc.
require:
  - "#aywan/json-ast"

# Granting partial access to internal symbols, "as an exception".
allow-internal-access:
